MAX_LENGTH_NAME = 200
MAX_LENGTH_MEASUREMENT_UNIT = 200
MIN_QUANTITY = 1
DEFAULT_HEX_COLOR = '#FF0000'

# Константы для модели Recipe
MIN_COOKING_TIME = 1

# Константы для модели Tag
MAX_LENGTH_COLOR = 7
MAX_LENGTH_SLUG = 200

# Константы для модели User
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_PASSWORD = 150
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
